### ISSUE TITLE
Appimage 1.7.2 - AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by canonex** [berteh/ScribusGenerator#245]
In Debian 13 (trixie), using Scribus 1.7.2 as Appimage I receive this error:

```
Read the log file for more (in your home directory).Traceback (most recent call last):
File "<string>", line 175, in buttonOkHandler
File ".../ScribusGenerator-4.0/ScribusGeneratorBackend.py", line 160, in run
output_filenames =
self.generate_templates(root, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../ScribusGenerator-4.0/ScribusGeneratorBackend.py", line 380, in generate_templates
Pages_count = int(document_element.get('ANZ PAGES'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

The same set of files (sla+csv) are working on Scribus 1.6.5 as Flatpak producing the expected output.

nb. I have a symbolic link of the Appimage on /usr/local/bin/
`scribus -> /.../scribus-1.7.2-linux-x86_64_e87103e603c3aced75531d720d0c45bf.AppImage`

Thank you,
Riccardo
